 // Source code is unavailable, and was generated by the Fernflower decompiler.
package com.jkdr.abyssalascentdimensionpatcher.mixins.invokers;

import net.minecraft.core.BlockPos;
import net.minecraft.server.level.PlayerRespawnLogic;
import net.minecraft.server.level.ServerLevel;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.gen.Invoker;

@Mixin({PlayerRespawnLogic.class})
public interface MixinPlayerRespawnLogic {
   @Invoker("getOverworldRespawnPos")
   static BlockPos invokeGetOverworldRespawnPos(ServerLevel level, int x, int z) {
      throw new AssertionError();
   }
}
